[package]
name = "tezos_context"
version = "3.1.1"
authors = ["Branislav Kontur <branislav.kontur@viablesystems.io>"]
edition = "2021"
rust-version = "1.58"

[dependencies]
anyhow = "1.0"
blake2 = "0.9"
bincode = "1.3"
crc32fast = "1.3.0"
crossbeam-channel = "0.5"
fs_extra = "1.2.0"
hex = "0.4"
lazy_static = "1.4"
leb128 = "0.2"
libc = "0.2.65"
modular-bitfield = "0.11"
parking_lot = "0.12.0"
serde = { version = "1.0", features = ["derive"] }
slog = { version = "2.7", features = [
  "max_level_trace",
  "release_max_level_trace",
] }
static_assertions = "1.1"
tikv-jemallocator = "0.4.3"
tikv-jemalloc-ctl = "0.4.2"
rand = "0.8"
strum = "0.20"
strum_macros = "0.20"
thiserror = "1.0"
# Internal dependencies
tezos_api = { path = "../tezos-api" }
tezos_context_api = { path = "../context-api" }
tezos_spsc = { path = "../spsc" }
tezos_crypto_rs = { path = "../../../../sdk/rust/crypto/", default-features = false, features = [
  "std",
] }
tezos_timing = { path = "../timing" }

[dev-dependencies]
flate2 = "1.0"
serde_json = "1.0"
storage = { path = "../storage" }
