# SPDX-FileCopyrightText: 2023 Nomadic Labs <contact@nomadic-labs.com>
# SPDX-FileCopyrightText: 2023 Marigold <contact@marigold.dev>
# SPDX-FileCopyrightText: 2023-2025 Functori <contact@functori.com>
# SPDX-FileCopyrightText: 2023 PK Lab <contact@pklab.io>
# SPDX-FileCopyrightText: 2024 TriliTech <contact@trili.tech>
#
# SPDX-License-Identifier: MIT

[workspace]
resolver = "2"

members = [
  "ethereum",
  "kernel",
  "evm_execution",
  "indexable_storage",
  "logging",
  "storage",
  "revm",
  "runtime",
]

[workspace.dependencies]

# error handling
thiserror = "1.0"
anyhow = "1.0"

# types
primitive-types = { version = "0.12.1", default-features = false }
num-bigint = { version = "0.4", default-features = false }
num-traits = "0.2.8"
num-derive = "0.4"
ethereum = { version = "0.14.0", default-features = false }
ethbloom = { version = "0.13.0", default-features = false, features = ["rlp"] }
softfloat = "1.0.0"
bytes = "^1"
enum_dispatch = { version = "0.3.13" }

# serialization
hex = "0.4"
hex-literal = "0.4.1"
tezos_data_encoding = { version = "0.6", git = "https://gitlab.com/tezos/tezos.git", rev = "bf6400411c8e74fbd75e2e9500df99993aa124b2" }
const-decoder = { version = "0.3.0" }
rlp = "0.5.2"
nom = { version = "7.1", default-features = false }
serde = { version = "1.0", features = ["derive", "rc"] }

# ethereum VM
revm = { version = "29.0.0", default-features = false, features = [ "optional_eip3607" ] }
evm = { path = "../sputnikvm", default-features = false }
aurora-engine-modexp = { version = "1.0", default-features = false }
bn = { package = "substrate-bn", version = "0.6", default-features = false }

# crypto stuff
sha2 = { version = "0.10.6", default-features = false }
sha3 = { version = "0.10.6", default-features = false }
ripemd = { version = "0.1.3", default-features = false }
tezos_crypto_rs = { version = "0.6", git = "https://gitlab.com/tezos/tezos.git", rev = "bf6400411c8e74fbd75e2e9500df99993aa124b2", default-features = false }
libsecp256k1 = { version = "0.7", default-features = false, features = [
  "static-context",
  "hmac",
] }

# kernel crates
revm-etherlink = { package = "revm-etherlink-ebisu", path = "./revm" }
tezos_ethereum = { package = "tezos_ethereum_ebisu", path = "./ethereum" }
tezos_tezlink = { package = "tezos_tezlink_ebisu", path = "./tezos" }
evm-execution = { package = "evm-execution-ebisu", path = "./evm_execution" }
tezos-execution = { package = "tezos-execution-ebisu", path = "./tezos_execution" }
tezos-evm-logging = { package = "tezos-evm-logging-ebisu", path = "./logging" }
tezos-evm-runtime = { package = "tezos-evm-runtime-ebisu", path = "./runtime" }
tezos-indexable-storage = { package = "tezos-indexable-storage-ebisu", path = "./indexable_storage" }
tezos-storage = { package = "tezos-storage-ebisu", path = "./storage" }

# SDK
# we disable BLS, because we don’t need it and it is a roadblock for the native execution
tezos-smart-rollup = { git = "https://gitlab.com/tezos/tezos.git", rev = "bf6400411c8e74fbd75e2e9500df99993aa124b2", default-features = false, features = [
  "std",
  "crypto",
  "dlmalloc",
  "panic-hook",
  "data-encoding",
  "storage",
  "testing",
] }
tezos-smart-rollup-core = { git = "https://gitlab.com/tezos/tezos.git", rev = "bf6400411c8e74fbd75e2e9500df99993aa124b2" }
tezos-smart-rollup-host = { git = "https://gitlab.com/tezos/tezos.git", rev = "bf6400411c8e74fbd75e2e9500df99993aa124b2" }
tezos-smart-rollup-panic-hook = { git = "https://gitlab.com/tezos/tezos.git", rev = "bf6400411c8e74fbd75e2e9500df99993aa124b2" }
tezos-smart-rollup-entrypoint = { git = "https://gitlab.com/tezos/tezos.git", rev = "bf6400411c8e74fbd75e2e9500df99993aa124b2" }
tezos-smart-rollup-debug = { git = "https://gitlab.com/tezos/tezos.git", rev = "bf6400411c8e74fbd75e2e9500df99993aa124b2" }
tezos-smart-rollup-encoding = { git = "https://gitlab.com/tezos/tezos.git", rev = "bf6400411c8e74fbd75e2e9500df99993aa124b2", default-features = false, features = [
  "alloc",
  "tezos-encoding",
  "crypto",
] }
tezos-smart-rollup-installer-config = { git = "https://gitlab.com/tezos/tezos.git", rev = "bf6400411c8e74fbd75e2e9500df99993aa124b2" }
tezos-smart-rollup-mock = { git = "https://gitlab.com/tezos/tezos.git", rev = "bf6400411c8e74fbd75e2e9500df99993aa124b2" }
tezos-smart-rollup-storage = { git = "https://gitlab.com/tezos/tezos.git", rev = "bf6400411c8e74fbd75e2e9500df99993aa124b2" }

# property based testing
rand = { version = "0.8" }
proptest = { version = "1.0" }
pretty_assertions = { version = "1.4.0" }

# alloy
alloy-sol-types = { version = "=1.3.0", default-features = false, features = [
    "json",
] }
alloy-primitives = { version = "=1.3.0", default-features = false }

# mir without bls
mir = { git = "https://gitlab.com/tezos/tezos.git", rev = "c6a2505d04f85d16471098d127c1bff4354aef10", default-features = false }

# miscs
format_no_std = "1.2.0"

# kernel execution profiling
nop-macros = { version = "0.2.0" }
tracing = { version = "0.1.41", features = ["attributes"]}

[profile.release]
# Will apply heavy LTO which attempts to perform optimizations across all crates
# within the dependency graph.
lto = true

[profile.release-with-debug]
inherits = "release"
debug = true
