stages:
  - start
  - evm_node_releases

datadog_pipeline_trace:
  image: datadog/ci:v2.44.0
  stage: start
  tags:
  - gcp
  dependencies: []
  allow_failure: true
  timeout: 3 minutes
  interruptible: false
  script:
  - CI_MERGE_REQUEST_IID=${CI_MERGE_REQUEST_IID:-none}
  - DATADOG_SITE=datadoghq.eu datadog-ci tag --level pipeline --tags pipeline_type:$PIPELINE_TYPE
    --tags mr_number:$CI_MERGE_REQUEST_IID

include:
  - template: Jobs/Container-Scanning.gitlab-ci.yml


container_scanning:
  stage: evm_node_releases
  tags:
  - gcp
  script:
  - gtcs scan > scan.log
  - grep "Vulnerability DB:" -B2 -A4 scan.log
  needs: []
  artifacts:
    paths:
      - scan.log
  variables:
    CS_IMAGE: "tezos/tezos:octez-evm-node-v0.12"
    SECURE_LOG_LEVEL: "debug"
    CS_DOCKERFILE_PATH: "build.Dockerfile"
    GIT_STRATEGY: fetch
