[package]
name = "octez-evm-node-wasm-runtime"
version = "0.0.0-dev"
authors = ["Etherlink Core Engineers <contact@tezos.com>"]
edition = "2021"
resolver = "3"

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
ocaml-build = { version = "1.*", features = ["dune"] }

[dependencies]
hex = "*"
ocaml = { version = "1.2.1" }
wasmer = { path = "../../src/rust_deps/wasmer-3.3.0/lib/api", default-features = false, features = [
    "cranelift",
    "jit",
] }
wasmer-compiler-cranelift = { path = "../../src/rust_deps/wasmer-3.3.0/lib/compiler-cranelift" }
tezos_crypto_rs = { version = "0.6", git = "https://gitlab.com/tezos/tezos.git", rev = "bf6400411c8e74fbd75e2e9500df99993aa124b2", default-features = false }
log = "0.4"
env_logger = "0.11"
octez-riscv-api = { path = "../../src/riscv/api" }
librustzcash = { path = "../../src/rustzcash_deps" }
tezos-smart-rollup-core = { git = "https://gitlab.com/tezos/tezos.git", rev = "bf6400411c8e74fbd75e2e9500df99993aa124b2" }
tezos-smart-rollup-host = { git = "https://gitlab.com/tezos/tezos.git", rev = "bf6400411c8e74fbd75e2e9500df99993aa124b2" }
# Bifrost kernel
kernel-bifrost = { package = "evm_kernel_bifrost", path = "../kernel_bifrost/kernel", default-features = false }
runtime-bifrost = { package = "tezos-evm-runtime-bifrost", path = "../kernel_bifrost/runtime", default-features = false }
# Calypso
kernel-calypso = { package = "evm_kernel_calypso", path = "../kernel_calypso/kernel", default-features = false }
runtime-calypso = { package = "tezos-evm-runtime-calypso", path = "../kernel_calypso/runtime", default-features = false }
# Calypso 2
kernel-calypso2 = { package = "evm_kernel_calypso2", path = "../kernel_calypso2/kernel", default-features = false }
runtime-calypso2 = { package = "tezos-evm-runtime-calypso2", path = "../kernel_calypso2/runtime", default-features = false }
# Dionysus
kernel-dionysus = { package = "evm_kernel_dionysus", path = "../kernel_dionysus/kernel", default-features = false }
runtime-dionysus = { package = "tezos-evm-runtime-dionysus", path = "../kernel_dionysus/runtime", default-features = false }

# Dionysus R1
kernel-dionysus-r1 = { package = "evm_kernel_dionysus_r1", path = "../kernel_dionysus_r1/kernel", default-features = false }
runtime-dionysus-r1 = { package = "tezos-evm-runtime-dionysus-r1", path = "../kernel_dionysus_r1/runtime", default-features = false }
