[package]
name = "tezos-bindings"
version = "0.1.0"
edition = "2021"

[lib]
name = "tezos"
crate-type = [ "lib", "cdylib", "staticlib" ]

[[bin]]
name = "uniffi-bindgen"
path = "src/uniffi-bindgen.rs"

[dependencies]
tezos_crypto_rs = { path = "../../../sdk/rust/crypto", default-features = false, features = [
  "bls",
] }
uniffi = { version = "0.29", features = [ "cli" ] }
thiserror = "1.0"

[dev-dependencies]
uniffi = { version = "0.29", features = [ "build" ] }