[env]
HERMIT_LOG_LEVEL_FILTER = { value = "Warn", force = true }

[build]
target = "riscv64gc-unknown-hermit"

[target.riscv64gc-unknown-linux-musl]
linker = "riscv64-unknown-linux-musl-gcc"
rustflags = [
	"-C",
	"target-feature=+crt-static",
	"-C",
	"default-linker-libraries",
]
