[package]
name = "riscv-sandbox"
version = "0.0.0"
edition = "2024"

[[bin]]
name = "riscv-sandbox"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
clap.workspace = true
comfy-table.workspace = true
enum-tag.workspace = true
gdbstub.workspace = true
gdbstub_arch.workspace = true
itertools.workspace = true
meansd.workspace = true
numfmt.workspace = true
quanta.workspace = true
serde.workspace = true
serde_json.workspace = true
tezos-smart-rollup-encoding.workspace = true
tezos-smart-rollup.workspace = true

[dependencies.octez-riscv]
path = "../lib"

[dependencies.tracing-subscriber]
workspace = true
optional = true

[features]
default = []
inline-jit = []
outline-jit = []
metrics = ["octez-riscv/metrics"]
log = ["octez-riscv/log", "dep:tracing-subscriber"]
