# SPDX-FileCopyrightText: 2025 Functori <contact@functori.com>
#
# SPDX-License-Identifier: MIT

[package]
name = 'revm-etherlink-poc'
version = '0.1.0'
edition = '2021'
license = "MIT"

[dependencies]

# VM
revm = { version = "25.0.0", default-features = false }

# Types
primitive-types.workspace = true
tezos_ethereum.workspace = true

# SDK
tezos-evm-runtime.workspace = true
tezos-smart-rollup-host.workspace = true
tezos-smart-rollup-storage.workspace = true

# Miscs
format_no_std = { version = "1.2.0" }
