[package]
name = "tezos_context_api"
version = "3.1.1"
edition = "2021"
rust-version = "1.58"
authors = ["Bruno Deferrari <bruno.deferrari@viablesystems.io>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_builder = "0.9"
time = { version = "0.3", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
strum = "0.20"
strum_macros = "0.20"
nom = "6.1"
# local dependencies
tezos_crypto_rs = { path = "../../../../sdk/rust/crypto/", default-features = false, features = [
  "std",
] }
tezos_data_encoding = { path = "../../../../sdk/rust/encoding" }
tezos_base = { path = "../tezos-base/" }
fuzzcheck = { git = "https://github.com/tezedge/fuzzcheck-rs.git", optional = true }
